spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ums
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: false


  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true
